baseURL = "https://trnglina.org"
languageCode = "en-gb"
title = "trnglina"

[params]
  author = "trnglina"
  description = "Software, design, and words"

[taxonomies]
  tag = "tags"

[markup.goldmark.renderer]
  unsafe = true
