baseURL = "https://trnglina.org"
languageCode = "en-gb"
title = "trnglina"

ignoreFiles = [ ".git/.*" ]

[params]
  author = "trnglina"
  description = "Software, design, and words"

[markup.goldmark.renderer]
  unsafe = true
