baseURL = "https://trnglina.org"
languageCode = "en-gb"
title = "Trnglina"

ignoreFiles = [ ".git/.*" ]

[params]
  author = "Trnglina"
  description = "Software, design, and words"

[menu]
  [[menu.index]]
    name = "Posts"
    url = "/posts"
    weight = 1
  [[menu.index]]
    name = "Work"
    url = "/work"
    weight = 2
  [[menu.index]]
    name = "About"
    url = "/about"
    weight = 4
  [[menu.index]]
    name = "Contact"
    url = "/contact"
    weight = 5
  [[menu.index]]
    name = "Privacy"
    url = "/privacy"
    weight = 6

[markup.goldmark.renderer]
  unsafe = true
