baseURL = "https://trnglina.org"
languageCode = "en-gb"
title = "Trnglina"

ignoreFiles = [ ".git/.*" ]

[params]
  author = "Trnglina"
  description = "Software, design, and words"

[menu]
  [[menu.index]]
    name = "Posts"
    url = "/posts"
    weight = 1
  [[menu.index]]
    name = "Works"
    url = "/works"
    weight = 2
  [[menu.index]]
    name = "About"
    url = "/about"
    weight = 3

[markup.goldmark.renderer]
  unsafe = true
