baseURL = "https://trnglina.org"
languageCode = "en-gb"
title = "Trnglina"

ignoreFiles = [ ".git/.*" ]

[params]
  author = "Trnglina"
  description = "Software, design, and words"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About Me"
    url = "/about"
    weight = 2

[markup.goldmark.renderer]
  unsafe = true
